package com.bsep.pki.model.dto;

import jakarta.validation.constraints.NotBlank;
import lombok.Data;

@Data
public class SavePublicKeyRequest {
    /**
     * RSA public key in SPKI PEM format (-----BEGIN PUBLIC KEY-----).
     * Generated by the browser via window.crypto.subtle.exportKey("spki", key).
     */
    @NotBlank(message = "Public key must not be blank")
    private String publicKeySpki;
}

