spring.application.name=pki
# Server
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5433/bsep_pki
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=bsep-super-tajni-kljuc-minimum-32-karaktera
jwt.expiry.hours=24

# Mail (za sad ostavi placeholder)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=placeholder@gmail.com
spring.mail.password=placeholder
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration